export const AJAX_CALL_BEGIN = "AJAX_CALL_BEGIN";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

export const LINES_GETALL_SUCCESS = "LINES_GETALL_SUCCESS";
export const LINES_SELECT = "LINES_SELECT";
