export const AJAX_CALL_BEGIN = "AJAX_CALL_BEGIN";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

export const USER_GET_PROFILE_SUCCESS = "USER_GET_PROFILE_SUCCESS";

export const LINES_GETALL_SUCCESS = "LINES_GETALL_SUCCESS";
export const LINES_SELECT = "LINES_SELECT";
export const LINES_GET_DETAIL_SUCCESS = "LINES_GET_DETAIL_SUCCESS";
